<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\SalesRule\Model\Coupon;
use Magento\SalesRule\Model\ResourceModel\Rule\Collection;
use Magento\TestFramework\Helper\Bootstrap;

$this->_collection = Bootstrap::getObjectManager()->create(
    Collection::class
);
$items = array_values($this->_collection->getItems());

// type SPECIFIC with code
$coupon = Bootstrap::getObjectManager()->create(Coupon::class);
$coupon->setRuleId($items[0]->getId())->setCode('coupon_code')->setType(0)->save();

// type NO_COUPON with non actual previously generated coupon codes
$coupon = Bootstrap::getObjectManager()->create(Coupon::class);
$coupon->setRuleId($items[1]->getId())->setCode('autogenerated_2_1')->setType(1)->save();
$coupon = Bootstrap::getObjectManager()->create(Coupon::class);
$coupon->setRuleId($items[1]->getId())->setCode('autogenerated_2_2')->setType(1)->save();

// type SPECIFIC with generated coupons
$coupon = Bootstrap::getObjectManager()->create(Coupon::class);
$coupon->setRuleId($items[2]->getId())->setCode('autogenerated_3_1')->setType(1)->save();
$coupon = Bootstrap::getObjectManager()->create(Coupon::class);
$coupon->setRuleId($items[2]->getId())->setCode('autogenerated_3_2')->setType(1)->save();

// type AUTO
$coupon = Bootstrap::getObjectManager()->create(Coupon::class);
$coupon->setRuleId($items[3]->getId())->setCode('coupon_code_auto')->setType(1)->save();
