<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var \Magento\Theme\Block\Html\Breadcrumbs $block */
/** @var Breadcrumbs $viewModel */

use Magento\Catalog\ViewModel\Product\Breadcrumbs;
use Magento\Framework\Json\Helper\Data;

$viewModel = $block->getData('viewModel');
?>
<div class="breadcrumbs"></div>
<?php
$widget = $this->helper(Data::class)->jsonDecode($viewModel->getJsonConfigurationHtmlEscaped());
$widgetOptions = $this->helper(Data::class)->jsonEncode($widget['breadcrumbs']);
?>
<script type="text/x-magento-init">
    {
        ".breadcrumbs": {
            "breadcrumbs": <?= /* @noEscape */
    $widgetOptions ?>
        }
    }

</script>
