<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Ui\Block\Wrapper;

?>
<?php
// phpcs:disable Magento2.PHP.ShortEchoSyntax.ShortEchoTag

/** @var $block Wrapper */
?>

<?php /* @noEscape */
echo $block->renderApp(
    [
        'widget_columns' => [
            'displayMode' => 'grid'
        ],
        'image' => [
            'imageCode' => 'recently_compared_products_grid_content_widget'
        ]
    ]
);
