<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * Products viewed counter template
 *
 * @var $block ProductViewCounter
 */

use Magento\Catalog\Block\Ui\ProductViewCounter;

?>
<script type="text/x-magento-init">
    {
        "*": {
                "Magento_Catalog/js/product/view/provider": {
                    "data": <?= /* @noEscape */
    $block->getCurrentProductData() ?>
            }
        }
    }

</script>
