<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Catalog\Block\Product\AbstractProduct;
use Magento\Catalog\Pricing\Price\FinalPrice;
use Magento\Framework\Pricing\Render;

?>
<?php /** @var AbstractProduct $block */ ?>
<?php $_product = $block->getProduct() ?>
<?= $block->getProductPriceHtml(
    $_product,
    FinalPrice::PRICE_CODE,
    Render::ZONE_ITEM_VIEW,
    [
        'price_id_suffix' => '_clone'
    ]
) ?>
