<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\BlockInterface;

?>
<?php
// phpcs:disable
?>
<?php
/**
 * Template meant for testing.
 *
 * @var BlockInterface $block
 * @var Escaper $escaper
 */
?>
<p>This template has access to <?= $escaper->escapeHtml('<b>$escaper</b>') ?> and $block &quot;<?= $block->toHtml() ?>
    &quot;</p>
